
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 15:37:09 IST (Sep  8 2019 10:07:09 UTC)

// Verification Directory fv/one_two_demux 

module one_two_demux(y0, y1, a, s0);
  input a, s0;
  output y0, y1;
  wire a, s0;
  wire y0, y1;
  NOR2BXL g17(.AN (a), .B (s0), .Y (y0));
  AND2XL g18(.A (s0), .B (a), .Y (y1));
endmodule

