
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 18:44:22 IST (Sep  8 2019 13:14:22 UTC)

// Verification Directory fv/three_eight_decoder 

module one_two_decoder_3(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2X1 g18(.A (e), .B (i0), .Y (y1));
endmodule

module one_two_decoder(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2X1 g18(.A (i0), .B (e), .Y (y1));
endmodule

module one_two_decoder_1(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2XL g18(.A (i0), .B (e), .Y (y1));
endmodule

module one_two_decoder_2(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2XL g18(.A (i0), .B (e), .Y (y1));
endmodule

module two_four_decoder(y0, y1, y2, y3, i0, i1, e);
  input i0, i1, e;
  output y0, y1, y2, y3;
  wire i0, i1, e;
  wire y0, y1, y2, y3;
  wire w_0, w_1;
  one_two_decoder A(w_0, w_1, i0, e);
  one_two_decoder_1 B(y0, y1, i1, w_0);
  one_two_decoder_2 C(y2, y3, i1, w_1);
endmodule

module one_two_decoder_4(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2X1 g18(.A (i0), .B (e), .Y (y1));
endmodule

module one_two_decoder_5(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2XL g18(.A (i0), .B (e), .Y (y1));
endmodule

module one_two_decoder_6(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2XL g18(.A (i0), .B (e), .Y (y1));
endmodule

module two_four_decoder_1(y0, y1, y2, y3, i0, i1, e);
  input i0, i1, e;
  output y0, y1, y2, y3;
  wire i0, i1, e;
  wire y0, y1, y2, y3;
  wire w_0, w_1;
  one_two_decoder_4 A(.y0 (w_0), .y1 (w_1), .i0 (i0), .e (e));
  one_two_decoder_5 B(.y0 (y0), .y1 (y1), .i0 (i1), .e (w_0));
  one_two_decoder_6 C(.y0 (y2), .y1 (y3), .i0 (i1), .e (w_1));
endmodule

module three_eight_decoder(y0, y1, y2, y3, y4, y5, y6, y7, i0, i1, i2,
     e);
  input i0, i1, i2, e;
  output y0, y1, y2, y3, y4, y5, y6, y7;
  wire i0, i1, i2, e;
  wire y0, y1, y2, y3, y4, y5, y6, y7;
  wire w_0, w_1;
  one_two_decoder_3 A(w_0, w_1, i0, e);
  two_four_decoder B(y0, y1, y2, y3, i1, i2, w_0);
  two_four_decoder_1 C(y4, y5, y6, y7, i1, i2, w_1);
endmodule

