
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 18:35:54 IST (Sep  8 2019 13:05:54 UTC)

// Verification Directory fv/two_four_decoder 

module one_two_decoder(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2X1 g18(.A (e), .B (i0), .Y (y1));
endmodule

module one_two_decoder_1(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2XL g18(.A (i0), .B (e), .Y (y1));
endmodule

module one_two_decoder_2(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2XL g18(.A (i0), .B (e), .Y (y1));
endmodule

module two_four_decoder(y0, y1, y2, y3, i0, i1, e);
  input i0, i1, e;
  output y0, y1, y2, y3;
  wire i0, i1, e;
  wire y0, y1, y2, y3;
  wire w_0, w_1;
  one_two_decoder A(w_0, w_1, i0, e);
  one_two_decoder_1 B(y0, y1, i1, w_0);
  one_two_decoder_2 C(y2, y3, i1, w_1);
endmodule

