
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  9 2019 23:02:21 IST (Sep  9 2019 17:32:21 UTC)

// Verification Directory fv/priority_encoder 

module priority_encoder(y0, y1, y2, v, e, x0, x1, x2, x3, x4, x5, x6,
     x7);
  input e, x0, x1, x2, x3, x4, x5, x6, x7;
  output y0, y1, y2, v;
  wire e, x0, x1, x2, x3, x4, x5, x6, x7;
  wire y0, y1, y2, v;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11;
  OAI31XL g291(.A0 (n_8), .A1 (x6), .A2 (n_11), .B0 (n_1), .Y (y0));
  NAND2BXL g292(.AN (y2), .B (n_10), .Y (v));
  AOI2BB1XL g295(.A0N (x4), .A1N (n_5), .B0 (x5), .Y (n_11));
  OAI31XL g294(.A0 (x1), .A1 (x0), .A2 (n_4), .B0 (e), .Y (n_10));
  OAI31XL g293(.A0 (n_3), .A1 (n_8), .A2 (n_7), .B0 (n_6), .Y (y1));
  OAI2BB1XL g296(.A0N (e), .A1N (n_7), .B0 (n_6), .Y (y2));
  AOI21XL g298(.A0 (x6), .A1 (e), .B0 (n_2), .Y (n_6));
  AOI21XL g297(.A0 (x1), .A1 (n_0), .B0 (x3), .Y (n_5));
  INVXL g301(.A (n_3), .Y (n_4));
  INVXL g299(.A (n_1), .Y (n_2));
  NAND2XL g300(.A (x7), .B (e), .Y (n_1));
  NOR2XL g302(.A (x3), .B (x2), .Y (n_3));
  OR2X1 g303(.A (x5), .B (x4), .Y (n_7));
  INVXL g305(.A (e), .Y (n_8));
  INVXL g304(.A (x2), .Y (n_0));
endmodule

