
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 23:16:22 IST (Sep  4 2019 17:46:22 UTC)

// Verification Directory fv/one_not 

module one_not(a, y);
  input a;
  output y;
  wire a;
  wire y;
  INVXL g2(.A (a), .Y (y));
endmodule

