
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 23:22:03 IST (Sep  4 2019 17:52:03 UTC)

// Verification Directory fv/one_xor 

module one_xor(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  CLKXOR2X1 g9(.A (b), .B (a), .Y (y));
endmodule

