
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  3 2019 20:02:45 IST (Sep  3 2019 14:32:45 UTC)

// Verification Directory fv/two_a 

module two_a(a, b, c, d, y);
  input a, b, c, d;
  output y;
  wire a, b, c, d;
  wire y;
  AO22X1 g20(.A0 (d), .A1 (c), .B0 (b), .B1 (a), .Y (y));
endmodule

