
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 15:50:45 IST (Sep  8 2019 10:20:45 UTC)

// Verification Directory fv/one_eight_demux 

module one_two_demux_3(y0, y1, a, s0);
  input a, s0;
  output y0, y1;
  wire a, s0;
  wire y0, y1;
  NOR2BXL g17(.AN (a), .B (s0), .Y (y0));
  AND2X1 g18(.A (s0), .B (a), .Y (y1));
endmodule

module one_two_demux(y0, y1, a, s0);
  input a, s0;
  output y0, y1;
  wire a, s0;
  wire y0, y1;
  NOR2BXL g17(.AN (a), .B (s0), .Y (y0));
  AND2X1 g18(.A (s0), .B (a), .Y (y1));
endmodule

module one_two_demux_1(y0, y1, a, s0);
  input a, s0;
  output y0, y1;
  wire a, s0;
  wire y0, y1;
  NOR2BXL g17(.AN (a), .B (s0), .Y (y0));
  AND2XL g18(.A (s0), .B (a), .Y (y1));
endmodule

module one_two_demux_2(y0, y1, a, s0);
  input a, s0;
  output y0, y1;
  wire a, s0;
  wire y0, y1;
  NOR2BXL g17(.AN (a), .B (s0), .Y (y0));
  AND2XL g18(.A (s0), .B (a), .Y (y1));
endmodule

module one_four_demux(y0, y1, y2, y3, a, s0, s1);
  input a, s0, s1;
  output y0, y1, y2, y3;
  wire a, s0, s1;
  wire y0, y1, y2, y3;
  wire w_0, w_1;
  one_two_demux A(w_0, w_1, a, s1);
  one_two_demux_1 B(y0, y1, w_0, s0);
  one_two_demux_2 C(y2, y3, w_1, s0);
endmodule

module one_two_demux_4(y0, y1, a, s0);
  input a, s0;
  output y0, y1;
  wire a, s0;
  wire y0, y1;
  NOR2BXL g17(.AN (a), .B (s0), .Y (y0));
  AND2X1 g18(.A (s0), .B (a), .Y (y1));
endmodule

module one_two_demux_5(y0, y1, a, s0);
  input a, s0;
  output y0, y1;
  wire a, s0;
  wire y0, y1;
  NOR2BXL g17(.AN (a), .B (s0), .Y (y0));
  AND2XL g18(.A (s0), .B (a), .Y (y1));
endmodule

module one_two_demux_6(y0, y1, a, s0);
  input a, s0;
  output y0, y1;
  wire a, s0;
  wire y0, y1;
  NOR2BXL g17(.AN (a), .B (s0), .Y (y0));
  AND2XL g18(.A (s0), .B (a), .Y (y1));
endmodule

module one_four_demux_1(y0, y1, y2, y3, a, s0, s1);
  input a, s0, s1;
  output y0, y1, y2, y3;
  wire a, s0, s1;
  wire y0, y1, y2, y3;
  wire w_0, w_1;
  one_two_demux_4 A(.y0 (w_0), .y1 (w_1), .a (a), .s0 (s1));
  one_two_demux_5 B(.y0 (y0), .y1 (y1), .a (w_0), .s0 (s0));
  one_two_demux_6 C(.y0 (y2), .y1 (y3), .a (w_1), .s0 (s0));
endmodule

module one_eight_demux(y0, y1, y2, y3, y4, y5, y6, y7, a, s0, s1, s2);
  input a, s0, s1, s2;
  output y0, y1, y2, y3, y4, y5, y6, y7;
  wire a, s0, s1, s2;
  wire y0, y1, y2, y3, y4, y5, y6, y7;
  wire w_0, w_1;
  one_two_demux_3 A(w_0, w_1, a, s2);
  one_four_demux B(y0, y1, y2, y3, w_0, s0, s1);
  one_four_demux_1 C(y4, y5, y6, y7, w_1, s0, s1);
endmodule

