
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 23:27:33 IST (Sep  4 2019 17:57:33 UTC)

// Verification Directory fv/one_xnor 

module one_xnor(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  wire n_0;
  OAI21XL g9(.A0 (a), .A1 (b), .B0 (n_0), .Y (y));
  NAND2XL g10(.A (b), .B (a), .Y (n_0));
endmodule

