
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  7 2019 19:11:48 IST (Sep  7 2019 13:41:48 UTC)

// Verification Directory fv/two_one_mux 

module two_one_mux(op, a, b, sel);
  input a, b, sel;
  output op;
  wire a, b, sel;
  wire op;
  MX2X1 g24(.A (a), .B (b), .S0 (sel), .Y (op));
endmodule

