
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  3 2019 19:52:34 IST (Sep  3 2019 14:22:34 UTC)

// Verification Directory fv/two_b 

module two_b(a, b, c, d, e, f, y);
  input a, b, c, d, e, f;
  output y;
  wire a, b, c, d, e, f;
  wire y;
  wire n_0;
  NOR2BXL g48(.AN (f), .B (n_0), .Y (y));
  AOI32XL g49(.A0 (c), .A1 (b), .A2 (a), .B0 (d), .B1 (e), .Y (n_0));
endmodule

