
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  8 2019 18:27:36 IST (Sep  8 2019 12:57:36 UTC)

// Verification Directory fv/one_two_decoder 

module one_two_decoder(y0, y1, i0, e);
  input i0, e;
  output y0, y1;
  wire i0, e;
  wire y0, y1;
  NOR2BXL g17(.AN (e), .B (i0), .Y (y0));
  AND2XL g18(.A (e), .B (i0), .Y (y1));
endmodule

