
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 26 2019 17:19:28 IST (Sep 26 2019 11:49:28 UTC)

// Verification Directory fv/FA 

module FA(c_out, sum, x, y, c_in);
  input x, y, c_in;
  output c_out, sum;
  wire x, y, c_in;
  wire c_out, sum;
  ADDFX1 g2(.A (c_in), .B (y), .CI (x), .CO (c_out), .S (sum));
endmodule

