
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 23:00:20 IST (Sep  4 2019 17:30:20 UTC)

// Verification Directory fv/one_nand 

module one_nand(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  NAND2XL g4(.A (b), .B (a), .Y (y));
endmodule

