
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 23:08:53 IST (Sep  4 2019 17:38:53 UTC)

// Verification Directory fv/one_nor 

module one_nor(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  NOR2XL g7(.A (b), .B (a), .Y (y));
endmodule

