
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  7 2019 19:44:19 IST (Sep  7 2019 14:14:19 UTC)

// Verification Directory fv/four_one_mux 

module two_one_mux(op, a, b, sel);
  input a, b, sel;
  output op;
  wire a, b, sel;
  wire op;
  MX2X1 g24(.A (a), .B (b), .S0 (sel), .Y (op));
endmodule

module two_one_mux_1(op, a, b, sel);
  input a, b, sel;
  output op;
  wire a, b, sel;
  wire op;
  MX2X1 g24(.A (a), .B (b), .S0 (sel), .Y (op));
endmodule

module two_one_mux_2(op, a, b, sel);
  input a, b, sel;
  output op;
  wire a, b, sel;
  wire op;
  MX2X1 g24(.A (a), .B (b), .S0 (sel), .Y (op));
endmodule

module four_one_mux(op, a, b, c, d, sel0, sel1);
  input a, b, c, d, sel0, sel1;
  output op;
  wire a, b, c, d, sel0, sel1;
  wire op;
  wire mux2_1, mux2_2;
  two_one_mux A(mux2_1, a, b, sel0);
  two_one_mux_1 B(mux2_2, c, d, sel0);
  two_one_mux_2 C(op, mux2_1, mux2_2, sel1);
endmodule

