
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 27 2019 11:20:46 IST (Sep 27 2019 05:50:46 UTC)

// Verification Directory fv/CLA 

module CLA(c_out, sum, x, y, c_in);
  input [3:0] x, y;
  input c_in;
  output c_out;
  output [3:0] sum;
  wire [3:0] x, y;
  wire c_in;
  wire c_out;
  wire [3:0] sum;
  wire n_0, n_1, n_2, n_5, n_6, n_8, n_9;
  OAI21XL g352(.A0 (n_8), .A1 (n_9), .B0 (n_0), .Y (c_out));
  MXI2XL g353(.A (n_1), .B (n_9), .S0 (n_8), .Y (sum[3]));
  AOI22XL g354(.A0 (n_5), .A1 (n_6), .B0 (x[2]), .B1 (y[2]), .Y (n_8));
  CLKXOR2X1 g355(.A (n_6), .B (n_5), .Y (sum[2]));
  ADDFX1 g356(.A (y[1]), .B (x[1]), .CI (n_2), .CO (n_5), .S (sum[1]));
  ADDFX1 g357(.A (y[0]), .B (x[0]), .CI (c_in), .CO (n_2), .S (sum[0]));
  INVXL g358(.A (n_1), .Y (n_9));
  CLKXOR2X1 g359(.A (y[3]), .B (x[3]), .Y (n_1));
  CLKXOR2X1 g360(.A (y[2]), .B (x[2]), .Y (n_6));
  NAND2XL g361(.A (y[3]), .B (x[3]), .Y (n_0));
endmodule

