
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 26 2019 18:29:54 IST (Sep 26 2019 12:59:54 UTC)

// Verification Directory fv/CRA 

module FA(c_out, sum, x, y, c_in);
  input x, y, c_in;
  output c_out, sum;
  wire x, y, c_in;
  wire c_out, sum;
  ADDFX1 g2(.A (c_in), .B (y), .CI (x), .CO (c_out), .S (sum));
endmodule

module FA_1(c_out, sum, x, y, c_in);
  input x, y, c_in;
  output c_out, sum;
  wire x, y, c_in;
  wire c_out, sum;
  ADDFX1 g2(.A (y), .B (x), .CI (c_in), .CO (c_out), .S (sum));
endmodule

module FA_2(c_out, sum, x, y, c_in);
  input x, y, c_in;
  output c_out, sum;
  wire x, y, c_in;
  wire c_out, sum;
  ADDFX1 g2(.A (y), .B (x), .CI (c_in), .CO (c_out), .S (sum));
endmodule

module FA_3(c_out, sum, x, y, c_in);
  input x, y, c_in;
  output c_out, sum;
  wire x, y, c_in;
  wire c_out, sum;
  ADDFX1 g2(.A (y), .B (x), .CI (c_in), .CO (c_out), .S (sum));
endmodule

module CRA(c_out, sum, x, y, c_in);
  input [3:0] x, y;
  input c_in;
  output c_out;
  output [3:0] sum;
  wire [3:0] x, y;
  wire c_in;
  wire c_out;
  wire [3:0] sum;
  wire w_1, w_2, w_3;
  FA A(w_1, sum[0], x[0], y[0], c_in);
  FA_1 B(w_2, sum[1], x[1], y[1], w_1);
  FA_2 C(w_3, sum[2], x[2], y[2], w_2);
  FA_3 D(c_out, sum[3], x[3], y[3], w_3);
endmodule

