
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 22:44:10 IST (Sep  4 2019 17:14:10 UTC)

// Verification Directory fv/one_and 

module one_and(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2XL g8(.A (b), .B (a), .Y (y));
endmodule

